// Copyright (c) 2023-2025 Koji Hasegawa.
// This software is released under the MIT License.

namespace TestHelper.Statistics.RandomGenerators
{
    /// <summary>
    /// Xorshift pseudo-random number generator.
    /// </summary>
    /// <remarks>
    /// Generated by Copilot.
    /// </remarks>
    public class Xorshift
    {
        private uint _x;
        private uint _y;
        private uint _z;
        private uint _w;

        public Xorshift(uint seed)
        {
            _x = seed;
            _y = 362436069;
            _z = 521288629;
            _w = 88675123;
        }

        public uint Next()
        {
            var t = _x ^ (_x << 11);
            _x = _y;
            _y = _z;
            _z = _w;
            _w = (_w ^ (_w >> 19)) ^ (t ^ (t >> 8));
            return _w;
        }
    }
}
